#!/usr/bin/env bash
set -e

# Dodanie repo Microsoftu
wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
sudo apt-get update

# Instalacja runtime (z APT)
sudo apt-get install -y aspnetcore-runtime-9.0

# Instalacja SDK (ze skryptu Microsoftu)
wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
chmod +x dotnet-install.sh
sudo ./dotnet-install.sh --channel 9.0 --install-dir /usr/share/dotnet
sudo ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet

# Weryfikacja
dotnet --info

